[workspace]
authors = ["killett <killett@jpl.nasa.gov>"]
channels = ["conda-forge"]
name = "scripts"
platforms = ["linux-64", "osx-arm64", "osx-64"]
version = "0.1.0"
exclude-newer = "7d"

[tasks]

[dependencies]
python = "3.12.*"
requests = "*"
cartopy = "*"
earthaccess = "*"
python-dateutil = "*"
s3fs = "*"
pandas = "*"
openpyxl = "*"
pillow = "*"
netcdf4 = "*"
unidecode = "*"
tqdm = "*"
gdal = "3.11.*"
astropy = "*"
xarray = "*"
dask = "*"
h5netcdf = "*"
matplotlib = "*"
pyproj = "*"
numpy = "*"
